### ISSUE TITLE
Update Issue Labels to match Rescue

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/sharinggoodapp#2]
We have a standard set of Github Issue Labels for all of our repos, but `sharinggoodapp` doesn't have them just yet! Can you remove the existing labels, and add our standard set, with appropriate emojis + colors?

**Comment by oroghene** [comment]
I have updated the labels for the `sharinggood` repo. None of the issues was labelled before I made the update. I left the issues without labels.

**Comment by ryanmarshallmc** [comment]
Perfect! Can you also do this for the `sharingexcess/.github` repo?
Thanks Roghe 👍

**Comment by oroghene** [comment]
Thank you. I will do that.

**Comment by oroghene** [comment]
I have updated the labels for the `sharingexcess/.github` repo. None of the issues was labelled before I made the update. I left the issues without labels.
