### ISSUE TITLE
Add Styling to Login + Edit Profile User Flow

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/sharinggoodapp#8]

**Comment by oroghene** [comment]
Code styling for `login`, `auth waiting`, and `edit profile v4` mobile views.

`login`
<img width="347" alt="Screen Shot 2022-04-08 at 4 54 59 PM" src="https://user-images.githubusercontent.com/73497649/162528683-34ae326f-02df-44d6-9dbd-3ae35ccc66ff.png">

`auth waiting`
<img width="343" alt="Screen Shot 2022-04-08 at 4 55 46 PM" src="https://user-images.githubusercontent.com/73497649/162528783-12378d1c-ec80-4e08-a7f2-8f69aa245846.png">

`edit profile v4`
<img width="346" alt="Screen Shot 2022-04-08 at 4 56 43 PM" src="https://user-images.githubusercontent.com/73497649/162528900-454e1a60-8f0a-45bf-9386-45c8e428db00.png">
